services:
  redis:
    image: "redis/redis-stack-server:latest"
    hostname: redis
    ports:
      - "6379:6379"
      - "8001:8001" # For RedisInsight (optional)
    volumes:
      - redis_data:/data
    networks:
      - polymarket_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - polymarket_network

  data_raw_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "sleep 10 && PYTHONPATH=. rq worker data.raw --url redis://redis:6379"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - polymarket_network

  initial_news_collector:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "sleep 15 && PYTHONPATH=. python collectors/news_collector.py"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - polymarket_network

volumes:
  redis_data:

networks:
  polymarket_network:
    driver: bridge
